### ISSUE TITLE
Tree detection error - dbscan

### ISSUE THREAD

**Issue by jazstoddart** [Molina-Valero/FORTLS#13]
Hi, 
Trying to use FORTLS to extract tree metrics within a SLAM generated las file.
Using the tree.detection.multi.scan function i encounter the following error during the "detecting tree stem axes" stage.

"_Error in dbscan::dbscan(eje.2[, c("x", "y"), drop = FALSE], eps = 0.25,  : 
  x needs to be a matrix or data.frame._"

My code is as follows.

```
library("FORTLS",attach.required = T)
wd<-MY PATH
setwd(wd)
#Normalise the input file.

Cloud <- normalize(las = ".\\Plot2_clip.las", 
                       x.center = 0, y.center = 0, RGB = FALSE,
                       scan.approach = "multi", file = "Plot2.txt",
                       dir.data = wd, save.result = FALSE)

tree.list<- tree.detection.multi.scan(data = Cloud[Cloud$prob.selec == 1, ],
                                                 dbh.min = 7, dbh.max = 200, h.min = 1.3,
                                                 ncr.threshold = 0.1,
                                                 tls.precision = 0.03,
                                                 breaks = 1.3, stem.section = c(1,5),
                                                 d.top = NULL,
                                                 plot.attributes = NULL,
                                                 save.result = FALSE, dir.result = NULL)

write.csv(tree.list, ".\\Outputs\\FORTLS_inventory_plot2.csv")
```

The normalization step works without issue and from what I can tell the error is a not due to my file as it is working with the environmental variable generated by the normalizations step.
Is the error internal or am I doing something wrong, I couldn't find anything in the documentation that suggested my code was incorrect.

Many thanks,
Jaz

**Comment by Molina-Valero** [comment]
Dear Jaz,

The code looks good. Which version of FORTLS are you working with?

The problems is happening when FORTLS is trying to estimate stem axes. Maybe because there are not points enough somehow. 

That may be related to the plot center coordinates. Are you sure plot center coordinates are x.center = 0 and y.center = 0? If so, the problem will be another. If not, maybe removing x.center = 0 and y.center = 0 arguments in the normalize function, or specifying realistic values for your point cloud, will work.

Also, if the point cloud is not very dense, working reduce point clouds (Cloud[Cloud$prob.selec == 1, ]) may be a drawback. 

I also suggest to use more breaks in order to increase the probability to detect trees. Removing the breaks argument you would get it.

If you still have problems, please let me know.

Best,
Juan
