### ISSUE TITLE
files with points below zero won't normalize

### ISSUE THREAD

**Issue by Estrada-Gene** [Molina-Valero/FORTLS#14]
I have 58  .las files that I collected using a FARO s350 TLS, taking multiple scans at each location, and using the FARO Scene software to register the multiple scans into a single point cloud for each of the 58 locations, exporting a .las file for each. The majority of them normalize fine using the automated FORTLS::tree.detection.several.plots() function. A handful of these files seem to get stuck at the 'normalize' step, freezing at 25% progress. I don't think this is a computer memory issue, since other files, some very large (3 - 4 GB) were analyzed with no issues. I ran the lidRr::las_check() function to look for any obvious issues, and the only thing that shows is that all of the problem files have some number of points below zero. I tried running the FORTLS::normalize() function for the individual files, setting the argument 'min.height = 0' but this didn't help at all. Do you have any recommendations for how to solve this? 

edit: I am using FORTLS v 1.2.0 and running the normalize function as follows, both with or without the 'min.height' argument:
ST5_norm <- normalize(las = "ST5.las",
                    scan.approach = "multi",
                    id = "ST5",
                    min.height = 0)

**Comment by Molina-Valero** [comment]
Hello,

I do not know exactly what to say, because the process of normalization is internally done by lidR functions. If you are able to normalize your .las files before (e.g. using the lidR package), then you can use the normalize function but including the argument "normalize = TRUE". The argument "min.height" is just to remove those points below of the specified value in the final normalized point cloud. But nothing to do with the normalization process. Could you please share with me one of the .las files showing problems to have a look? I can try to fix it.

Best,
Juan

**Comment by Estrada-Gene** [comment]
I can't attach them here, as the file size are too large, even after compressed. I have emailed you (juanalberto.molina.valero@usc.es) a few of the files that I'm having an issue with. Thanks a lot!

**Comment by Molina-Valero** [comment]
Sorry but my current email is molina_valero@fld.czu.cz

Best regards,
Juan

**Comment by Estrada-Gene** [comment]
OK, I've forwarded the message to your current email. Thank again.
